import argparse

def parse_config():
    parser = argparse.ArgumentParser()
    parser.add_argument('--sketch_dir', type=str)
    parser.add_argument('--image_dir', type=str)
    parser.add_argument('--stats_file', type=str)
    parser.add_argument('--packed_pkl_zs', type=str)
    parser.add_argument('--packed_pkl_nozs', type=str)
    parser.add_argument('--embedding_file', type=str)
    parser.add_argument('--preprocess_data', type=str)
    parser.add_argument('--raw_data', type=str)
    parser.add_argument('--log_file', type=str)
    parser.add_argument('--shuffle', action='store_true')
    parser.add_argument('--sample_times', type=int, default=10)

    parser.add_argument('--pca_size', type=int, default=2048)
    parser.add_argument('--raw_size', type=int, default=5568)
    parser.add_argument('--hidden_size', type=int, default=1024)
    parser.add_argument('--semantics_size', type=int, default=300)
    parser.add_argument('--fix_embedding', action='store_true')
    parser.add_argument('--seman_dist', type=str, default='cosine')
    parser.add_argument('--triplet_dist', type=str, default='l2')
    parser.add_argument('--margin', type=float, default=10.0)
    parser.add_argument('--margin1', type=float, default=1.0)
    parser.add_argument('--margin2', type=float, default=10.0)
    parser.add_argument('--patience', type=int, default=5)
    parser.add_argument('--batch_size', type=int, default=32)
    parser.add_argument('--num_worker', type=int, default=8)
    parser.add_argument('--dropout', type=float, default=0.2)
    parser.add_argument('--warmup_steps', type=int, default=100)
    parser.add_argument('--lr', type=float, default=1e-5)
    parser.add_argument('--l2_weight', type=float, default=0.005)
    parser.add_argument('--l1_weight', type=float, default=0.05)
    parser.add_argument('--print_every', type=int, default=100)
    parser.add_argument('--save_every', type=int, default=1000)
    parser.add_argument('--start_from', type=str, default=None)
    parser.add_argument('--save_dir', type=str)
    parser.add_argument('--gpu_id', type=int, default=0)
    parser.add_argument('--zs', action='store_true')
    parser.add_argument('--cum_num', type=int, default=3)

    return parser.parse_args()
