python ./src/main_cmdtrans.py  --packed_pkl_nozs ./data/sketchy/nozs_packed.pkl \
                               --packed_pkl_zs ./data/sketchy/zs_packed.pkl \
                               --embedding_file ./data/GoogleNews-vectors-negative300.bin \
                               --preprocess_data ./data/sketchy/sketchy_processed_5568.h5py \
                               --shuffle \
                               --sample_times 1 \
                               --semantics_size 300 \
                               --fix_embedding \
                               --seman_dist l2 \
                               --triplet_dist l2 \
                               --margin1 0.0 \
                               --margin2 10.0 \
                               --patience 20 \
                               --batch_size 64 \
                               --num_worker 0 \
                               --dropout 0.0 \
                               --warmup_steps 1000 \
                               --lr 2e-4 \
                               --print_every 100 \
                               --save_every 500 \
                               --raw_data ./data/sketchy/sketchy_processed_5568.h5py \
                               --raw_size 5568 \
                               --hidden_size 1024 \
                               --save_dir ./model/cmdtrans_sketchy_strong/ \
                               --log_file ./log/cmdtrans_sketchy_strong.log \
                               --gpu_id 1 \
                               --cum_num 1 \
                               --zs --strong_pair
